name: Daily picks
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Cache data (odds history)
        uses: actions/cache@v4
        with:
          path: data
          key: data-cache-${{ github.run_id }}
          restore-keys: |
            data-cache-
      - name: Checkout
        uses: actions/checkout@v4
