name: Daily FOOT picks (auto)

on:
  schedule:
    - cron: "0 8 * * *"   # ~10:00 Paris l'été
  workflow_dispatch: {}

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check repo
        run: |
          ls -la
          if [ -f cron_send_foot.py ]; then echo "Found cron_send_foot.py";
          elif [ -f cron_send.py ]; then echo "Found cron_send.py";
          else echo "❌ Aucun sender trouvé (cron_send_foot.py ou cron_send.py)"; exit 1; fi
          test -f requirements.txt || (echo "requirements.txt manquant" && exit 1)

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt

      - name: Smoke test (sans Telegram)
        env:
          ODDS_API_KEY:       ${{ secrets.ODDS_API_KEY }}
          TIMEZONE: Europe/Paris
          ODDS_REGIONS: eu,uk,us,au
          ODDS_FORMAT: decimal
          ODDS_DATE_FORMAT: iso
          MIN_EV: "0.02"
          MAX_PICKS: "3"
        run: |
          python - <<'PY'
          import os
          from odds_providers import fetch_soccer_odds
          df = fetch_soccer_odds()
          print("Fetched rows:", len(df))
          print(df.head(5).to_string() if not df.empty else "No rows.")
          PY

      - name: Run sender
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          ODDS_API_KEY:       ${{ secrets.ODDS_API_KEY }}
          TIMEZONE: Europe/Paris
          ODDS_REGIONS: eu,uk,us,au
          ODDS_FORMAT: decimal
          ODDS_DATE_FORMAT: iso
          MIN_EV: "0.02"
          MAX_PICKS: "3"
        run: |
          if [ -f cron_send_foot.py ]; then python cron_send_foot.py;
          elif [ -f cron_send.py ]; then python cron_send.py;
          else echo "❌ Aucun sender trouvé"; exit 1; fi
