name: Weekend FOOT report (top-5)

on:
  schedule:
    # Heures en UTC (Paris = UTC+1/2)
    - cron: "0 8 * * 5"   # Vendredi
    - cron: "0 14 * * 5"
    - cron: "0 18 * * 5"
    - cron: "0 8 * * 6"   # Samedi
    - cron: "0 14 * * 6"
    - cron: "0 18 * * 6"
    - cron: "0 8 * * 0"   # Dimanche
    - cron: "0 14 * * 0"
    - cron: "0 18 * * 0"
  workflow_dispatch: {}

jobs:
  weekend:
    runs-on: ubuntu-latest
    env:
      TIMEZONE: Europe/Paris
      WEEKEND_MIN_EV: "0.01"
      WEEKEND_STRICT: "1"          # 1 = impose le week-end courant/prochain
      WEEKEND_ALLOW_FALLBACK: "1"  # 1 = active le fallback si rien n’apparaît
      ODDS_SPORTS: soccer_epl,soccer_france_ligue_1,soccer_spain_la_liga,soccer_italy_serie_a,soccer_germany_bundesliga
      ODDS_REGIONS: eu,uk

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
      - name: Debug fetch (compte les événements par ligue)
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          ODDS_REGIONS: eu,uk
        run: |
          python - <<'PY'
          import os, requests
          key=os.environ['ODDS_API_KEY']
          regions=os.getenv('ODDS_REGIONS','eu')
          sports=[
            'soccer_france_ligue_1',
            'soccer_epl',
            'soccer_spain_la_liga',
            'soccer_italy_serie_a',
            'soccer_germany_bundesliga'
          ]
          for s in sports:
            url=f'https://api.the-odds-api.com/v4/sports/{s}/odds'
            params={'apiKey':key,'regions':regions,'markets':'h2h,totals','oddsFormat':'decimal','dateFormat':'iso'}
            try:
              r=requests.get(url, params=params, timeout=25)
              print(s, '->', r.status_code, 'events:', (len(r.json()) if r.ok else 'ERR'))
            except Exception as e:
              print(s, '-> EXC', e)
          PY
      - name: Debug The Odds API
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          ODDS_REGIONS: eu,uk
          ODDS_SPORTS: soccer_france_ligue_1,soccer_epl,soccer_spain_la_liga,soccer_italy_serie_a,soccer_germany_bundesliga
        run: |
          python debug_odds.py

      - name: Run weekend report
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          ODDS_API_KEY:       ${{ secrets.ODDS_API_KEY }}
          TIMEZONE: Europe/Paris
          ODDS_FORMAT: decimal
          ODDS_DATE_FORMAT: iso
          ODDS_REGIONS: eu,uk,us,au
          ODDS_SPORTS: soccer_epl,soccer_france_ligue_1,soccer_spain_la_liga,soccer_italy_serie_a,soccer_germany_bundesliga
          WEEKEND_MIN_EV: "0.01"
        run: |
          python weekend_send.py
