name: Weekend FOOT report (top-5)

on:
  # ⏰ Déclenchements automatiques (UTC)
  # -> Paris ≈ UTC+1 (hiver) / UTC+2 (été)
  schedule:
    - cron: "30 8 * * 5"   # Vendredi matin
    - cron: "30 15 * * 5"  # Vendredi après-midi
    - cron: "30 9 * * 6"   # Samedi matin
    - cron: "30 15 * * 6"  # Samedi après-midi
    - cron: "30 9 * * 0"   # Dimanche matin
    - cron: "30 15 * * 0"  # Dimanche après-midi
  # Lancer manuellement depuis l’onglet Actions
  workflow_dispatch: {}

jobs:
  weekend:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # ⚙️ Variables d'environnement
    env:
      # 🔒 Secrets (à créer dans Settings → Secrets → Actions)
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
      ODDS_API_KEY:       ${{ secrets.ODDS_API_KEY }}
      # Optionnel : plusieurs clés séparées par ';' (ex: "key1;key2")
      ODDS_API_KEYS:      ${{ secrets.ODDS_API_KEYS }}

      # 🔩 Paramètres du bot
      TIMEZONE: Europe/Paris
      WEEKEND_MIN_EV: "0.01"
      WEEKEND_STRICT: "1"           # n'analyse que ven→dim du WE courant/prochain
      WEEKEND_ALLOW_FALLBACK: "1"   # si vide, cherche WE suivant / 7 jours (mentionné dans le message)

      # 💾 Mode économe en crédits : 1 seule requête via /sports/upcoming/odds
      ODDS_USE_UPCOMING: "1"
      ODDS_REGIONS: eu,uk
      ODDS_SPORTS: soccer_epl,soccer_france_ligue_1,soccer_spain_la_liga,soccer_italy_serie_a,soccer_germany_bundesliga

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weekend report
        run: |
          python weekend_send.py
