name: Weekend FOOT report (top-5)

on:
  schedule:
    # Heures en UTC (Paris = UTC+1/2)
    - cron: "0 8 * * 5"   # Vendredi
    - cron: "0 14 * * 5"
    - cron: "0 18 * * 5"
    - cron: "0 8 * * 6"   # Samedi
    - cron: "0 14 * * 6"
    - cron: "0 18 * * 6"
    - cron: "0 8 * * 0"   # Dimanche
    - cron: "0 14 * * 0"
    - cron: "0 18 * * 0"
  workflow_dispatch: {}

jobs:
  weekend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
      - name: Run weekend report
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          ODDS_API_KEY:       ${{ secrets.ODDS_API_KEY }}
          TIMEZONE: Europe/Paris
          ODDS_FORMAT: decimal
          ODDS_DATE_FORMAT: iso
          ODDS_REGIONS: eu,uk,us,au
          ODDS_SPORTS: soccer_epl,soccer_france_ligue_1,soccer_spain_la_liga,soccer_italy_serie_a,soccer_germany_bundesliga
          WEEKEND_MIN_EV: "0.01"
        run: |
          python weekend_send.py
