name: Daily picks (v4-lite)

on:
  schedule:
    - cron: "0 8 * * *"     # ~10:00 Paris l'été
  workflow_dispatch: {}

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache data (odds history placeholder)
        uses: actions/cache@v4
        with:
          path: data
          key: data-cache-${{ github.run_id }}
          restore-keys: |
            data-cache-

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily sender (v4-lite)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          ODDS_API_KEY:       ${{ secrets.ODDS_API_KEY }}
          TIMEZONE: Europe/Paris
          # Coverage
          ODDS_REGIONS: eu,uk,us,au
          ODDS_MARKETS: h2h
          # Soft filters
          MIN_ODDS: "1.30"
          MIN_EDGE: "0.015"
          MIN_BOOKS: "2"
          BVM_TENNIS: "1.00"
          BVM_OTHER:  "0.995"
          MAX_ODDS_GLOBAL: "2.60"
          MIN_PROB_GLOBAL: "0.50"
          MIN_START_MINUTES: "15"
          MAX_START_HOURS: "72"
          # Bankroll
          BANKROLL_START: "100"
          KELLY_FRACTION: "0.20"
        run: |
          python cron_send.py
